from django.contrib import admin
from .models import *
# Register your models here.
admin.site.register(User)
admin.site.register(Profile)
admin.site.register(Todo)
admin.site.register(Blogs)
admin.site.register(Comment)
admin.site.register(Contact)
admin.site.register(TutorialName)
admin.site.register(TutorialPost)
admin.site.register(CodeSnippet)
admin.site.register(Topics)
admin.site.register(Language)
admin.site.register(Short)
admin.site.register(Problem_solve)
admin.site.register(Comment_tutorials)
admin.site.register(Latest_update)
admin.site.register(LanguageMcq)
admin.site.register(TopicMcq)
admin.site.register(Question)
admin.site.register(Option)
admin.site.register(Result)
admin.site.register(Category)